### ISSUE TITLE
Support for Variable Replaced Configuration

### ISSUE THREAD

**Issue by jhappoldt** [daniel-cottone/serverless-es-logs#199]
First, thank you for this very useful plugin!

It appears that the plugin does not support the case where the entire `custom` YAML block is replaced by an external file.  Given the below example:
```
serverless.yaml
custom: ${file(../../config/universal.yml):custom}
```
```
universal.yaml
custom:
  esLogs:
    endpoint: ${esEndpoint}
    index: logs
    retentionDays: 7
    tags:
      stack: ${opt:stage}
      service: ${self:service}
```

Serverless `deploy` throws `ERROR: No configuration provided for serverless-es-logs!`.  This is caused by destructuring inthe [validatePluginOptions](https://github.com/daniel-cottone/serverless-es-logs/blob/master/src/index.ts#L100) function.

I've been able to get the plugin to work in this scenario by replacing references to `this.custom` with `const { esLogs } = this.serverless.service.custom` after reading the [following thread](https://forum.serverless.com/t/serverless-plugin-resolving-variable-references/2233) on the official discussion forum.

I'm unfamiliar with serverless plugins but would be happy to make a PR with this change if it's agreeable.
