### ISSUE TITLE
The final policy size is bigger than the limit (20480) when too many endpoints exist

### ISSUE THREAD

**Issue by felipeparaujo** [daniel-cottone/serverless-es-logs#365]
I ran into  issue when setting up `serverless-es-logs` for a service with ~50 endpoints:

```
The final policy size (20827) is bigger than the limit (20480). (Service: AWSLambda; Status Code: 400; Error Code: PolicyLengthExceededException)
```

The policy for `EsLogsProcesserLambdaFunction` would go over the size limit because the plugin creates a single `CWPermission` for each endpoint. As a quick and dirty fix for this I forked this repo (please ignore the shamefully committed `dist` folder, when I say dirty I mean dirty) and commented out the subscription filter permission generation: https://github.com/immocapital/serverless-es-logs/blob/disable-individual-lambda-permissions/src/index.ts#L210-L228

Then, in my `serverless.yml`, file I added

```
resources:
  Resources:
    LambdaCloudWatchPermissions:
      Type: 'AWS::Lambda::Permission'
      Properties:
        Action: 'lambda:InvokeFunction'
        SourceAccount: '#{AWS::AccountId}'
        FunctionName:
          "Fn::GetAtt":
            - 'EsLogsProcesserNestedStack'
            - 'Outputs.EsLogsProcesserLambdaFunctionArn'
        Principal: 'logs.#{AWS::Region}.amazonaws.com'
        SourceArn: 'arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:log-group:/aws/lambda/${self:service}-${self:custom.stage}-*'
      DependsOn: 'EsLogsProcesserLambdaFunction'
```
(I use [`serverless-pseudo-parameters`](https://github.com/svdgraaf/serverless-pseudo-parameters) and [`serverless-plugin-split-stacks`](https://github.com/dougmoscrop/serverless-plugin-split-stacks), just to explain those #{AWS...} variables and `"Fn::GetAtt"` statement)

And this fixed the issue. This is by no means an ideal solution, so maybe adding an option to generate a single policy entry for the lambda would be a good idea.
